version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template-creator-app:latest
    depends_on:
      - pocketbase
      - gotenberg
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_POCKETBASE_URL: http://pocketbase:8090
      NEXT_PUBLIC_GOTENBERG_URL: http://gotenberg:3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  pocketbase:
    image: pocketbase/pocketbase:latest
    command: serve --http=0.0.0.0:8090
    volumes:
      - pb_data:/pb/pb_data
      - pb_public:/pb/pb_public
    ports:
      - "8090:8090"
    restart: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:8
    # Gotenberg listens on 3000 inside the container
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  pb_data:
  pb_public: